# Generated by Django 5.1 on 2025-06-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descrip', models.TextField()),
                ('img', models.URLField(verbose_name='URL compartida del drive')),
            ],
        ),
    ]
