# Generated by Django 5.1 on 2025-06-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='img',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='id_img',
            field=models.CharField(default='sin_imagen', max_length=2083),
        ),
    ]
